language: node_js
node_js: 
    - '7.6'

cache:
  directories:
    - node_modules


install:
  - npm i --global ava
  - npm i --save-dev ava
  - npm install --dependencies

before_script:

script:
  - npm run test

branches:
  only:
    - master
env:
 global:
